# ================================================================
# MRC MANUSCRIPT NARRATIVE — CLEANED RUN SCRIPT
# ================================================================
# Purpose:
#   Reruns the manuscript plotting/calculation environment, then uses the
#   original Results Narrative Exporter from the 40k-line analysis environment
#   to generate manuscript-facing Results prose and an audit CSV.
#
# Expected companion file:
#   MRC_manuscript_plots_cleaned.R
#
# Main outputs:
#   manuscript_narrative/Results_Narrative_AutoGenerated.txt
#   manuscript_narrative/Results_Narrative_Audit_Values.csv
#
# Notes:
#   - This script intentionally does not read the final manuscript text back in.
#   - It reruns/reuses the R objects created by the Figure 1–6 calculation code.
#   - Figure 6 is the exception where the final manuscript uses the ASC-only
#     baseline-aligned candidate-predictor version.
# ================================================================

# -----------------------------
# 0. User paths
# -----------------------------
DATA_DIR <- Sys.getenv("MRC_DATA_DIR", unset = "C:/Users/dn284/Desktop/MRC_omni/data")

OUTPUT_ROOT <- file.path(DATA_DIR, "MRC_public_outputs")
NARRATIVE_OUT_DIR <- file.path(OUTPUT_ROOT, "manuscript_narrative")
dir.create(NARRATIVE_OUT_DIR, recursive = TRUE, showWarnings = FALSE)

# The manuscript plot script should be the cleaned file produced earlier.
# The search order lets you either keep it beside this script or inside DATA_DIR.
SCRIPT_DIR <- tryCatch(dirname(normalizePath(sys.frame(1)$ofile)), error = function(e) getwd())
MANUSCRIPT_PLOTS_SCRIPT_CANDIDATES <- c(
  file.path(SCRIPT_DIR, "MRC_manuscript_plots_cleaned.R"),
  file.path(DATA_DIR, "MRC_manuscript_plots_cleaned.R"),
  file.path(getwd(), "MRC_manuscript_plots_cleaned.R")
)
MANUSCRIPT_PLOTS_SCRIPT <- MANUSCRIPT_PLOTS_SCRIPT_CANDIDATES[file.exists(MANUSCRIPT_PLOTS_SCRIPT_CANDIDATES)][1]

if (is.na(MANUSCRIPT_PLOTS_SCRIPT) || length(MANUSCRIPT_PLOTS_SCRIPT) == 0) {
  stop(
    "Could not find MRC_manuscript_plots_cleaned.R. ",
    "Place it beside this script, in DATA_DIR, or in the working directory."
  )
}

message("Using DATA_DIR: ", DATA_DIR)
message("Using manuscript plot/calculation script: ", MANUSCRIPT_PLOTS_SCRIPT)
message("Narrative outputs will be written to: ", NARRATIVE_OUT_DIR)

# -----------------------------
# 1. Packages
# -----------------------------
required_packages <- c(
  "tidyverse", "stringr", "readr", "tibble", "patchwork",
  "showtext", "sysfonts", "scales", "lubridate", "grid"
)
missing_packages <- required_packages[!vapply(required_packages, requireNamespace, logical(1), quietly = TRUE)]
if (length(missing_packages) > 0) {
  stop(
    "Missing required packages: ", paste(missing_packages, collapse = ", "),
    "\nInstall them, then rerun this script."
  )
}

suppressPackageStartupMessages({
  library(tidyverse)
  library(stringr)
  library(readr)
  library(tibble)
})

# -----------------------------
# 2. Run manuscript figure calculations
# -----------------------------
# This creates the objects expected below, including FLOW_COUNTS,
# wp1_session/wp1_long, stats_df/rank_summary/binom_p, retention_df,
# summary_tol, phq_summary, bdi_summary, and Figure 6 candidate-predictor objects.
source(MANUSCRIPT_PLOTS_SCRIPT, local = .GlobalEnv)

# -----------------------------
# 3. Original Results Narrative Exporter, cleaned only for output location
# -----------------------------
# RESULTS NARRATIVE EXPORTER
# Produces manuscript-ready Results prose using objects already
# created by Figures 1–6.
# ===================================================

library(tidyverse)
library(stringr)

# ===================================================
# SMALL FORMATTING HELPERS
# ===================================================

obj_exists <- function(x) exists(x, envir = .GlobalEnv)

safe_get <- function(x, default = NULL) {
  if (exists(x, envir = .GlobalEnv)) get(x, envir = .GlobalEnv) else default
}

fmt_n <- function(x) {
  if (length(x) == 0 || is.na(x)) return("NA")
  formatC(as.integer(round(x)), format = "d", big.mark = ",")
}

fmt_num <- function(x, digits = 2) {
  if (length(x) == 0 || is.na(x)) return("NA")
  formatC(as.numeric(x), format = "f", digits = digits)
}

fmt_pct <- function(x, digits = 1) {
  if (length(x) == 0 || is.na(x)) return("NA")
  paste0(formatC(as.numeric(x), format = "f", digits = digits), "%")
}

fmt_p <- function(p) {
  if (length(p) == 0 || is.na(p)) return("NA")
  if (p < .001) return("< .001")
  paste0("= ", formatC(p, format = "f", digits = 3))
}

fmt_signed <- function(x, digits = 2) {
  if (length(x) == 0 || is.na(x)) return("NA")
  out <- formatC(abs(as.numeric(x)), format = "f", digits = digits)
  ifelse(x >= 0, paste0("+", out), paste0("-", out))
}

direction_word <- function(change_score, improvement_is_positive = TRUE) {
  if (is.na(change_score)) return("no clear")
  if (improvement_is_positive) {
    if (change_score > 0) return("greater")
    if (change_score < 0) return("lesser")
  } else {
    if (change_score < 0) return("greater")
    if (change_score > 0) return("lesser")
  }
  "similar"
}

# ===================================================
# FIGURE 1 / PROGRAMME FLOW VALUES
# ===================================================

FLOW_COUNTS_local <- safe_get("FLOW_COUNTS")

if (is.null(FLOW_COUNTS_local)) {
  stop("FLOW_COUNTS was not found. Please run Figure 1 before this narrative exporter.")
}

wp1_screened_n     <- FLOW_COUNTS_local$WP1$screened
wp1_excluded_n     <- FLOW_COUNTS_local$WP1$excluded
wp1_tested_n       <- FLOW_COUNTS_local$WP1$tested
wp1_analysed_n     <- FLOW_COUNTS_local$WP1$analysed

interim_screened_n <- FLOW_COUNTS_local$Interim$screened
interim_excluded_n <- FLOW_COUNTS_local$Interim$excluded
interim_tested_n   <- FLOW_COUNTS_local$Interim$tested
interim_analysed_n <- FLOW_COUNTS_local$Interim$analysed

wp2_screened_n     <- FLOW_COUNTS_local$WP2$screened
wp2_excluded_n     <- FLOW_COUNTS_local$WP2$excluded
wp2_tested_n       <- FLOW_COUNTS_local$WP2$tested
wp2_analysed_n     <- FLOW_COUNTS_local$WP2$analysed

total_screened_n <- sum(
  wp1_screened_n,
  interim_screened_n,
  wp2_screened_n,
  na.rm = TRUE
)

total_analysed_n <- sum(
  wp1_analysed_n,
  interim_analysed_n,
  wp2_analysed_n,
  na.rm = TRUE
)

# ===================================================
# FIGURE 2 / WP1 SAFETY VALUES
# ===================================================

wp1_session_local <- safe_get("wp1_session")
wp1_long_local    <- safe_get("wp1_long")

highest_mean_local <- safe_get("highest_mean", NA_real_)
highest_ucl80_local <- safe_get("highest_ucl80", NA_real_)
highest_ucl80_session_local <- safe_get("highest_ucl80_session", NA_real_)

THRESHOLD_local <- safe_get("THRESHOLD", 7.0)

wp1_rows_above_threshold <- NA_integer_
wp1_ids_above_threshold  <- NA_integer_
wp1_any_side_effect_pct  <- NA_real_

if (!is.null(wp1_long_local)) {
  wp1_rows_above_threshold <- wp1_long_local %>%
    filter(!is.na(discomfort), discomfort >= THRESHOLD_local) %>%
    nrow()
  
  wp1_ids_above_threshold <- wp1_long_local %>%
    filter(!is.na(discomfort), discomfort >= THRESHOLD_local) %>%
    summarise(n = n_distinct(part_id)) %>%
    pull(n)
  
  if ("any_side_effect" %in% names(wp1_long_local)) {
    wp1_any_side_effect_pct <- 100 * mean(wp1_long_local$any_side_effect, na.rm = TRUE)
  }
}

wp1_threshold_sentence <- if (!is.na(wp1_rows_above_threshold) && wp1_rows_above_threshold == 0) {
  paste0(
    "No participant-session ratings exceeded the prespecified discontinuation threshold of ",
    fmt_num(THRESHOLD_local, 1),
    "/10."
  )
} else {
  paste0(
    fmt_n(wp1_rows_above_threshold),
    " participant-session ratings from ",
    fmt_n(wp1_ids_above_threshold),
    " participant(s) met or exceeded the prespecified discontinuation threshold of ",
    fmt_num(THRESHOLD_local, 1),
    "/10."
  )
}

# ===================================================
# FIGURE 3 / INTERIM VALUES
# Vector-safe
# ===================================================

stats_df_local     <- safe_get("stats_df")
rank_summary_local <- safe_get("rank_summary")
binom_p_local      <- safe_get("binom_p", NA_real_)

interim_control_rank_n <- NA_integer_
interim_intervention_rank_n <- NA_integer_
interim_total_rank_n <- NA_integer_

if (!is.null(rank_summary_local)) {
  interim_control_rank_n <- rank_summary_local %>%
    filter(as.character(condition) == "Control") %>%
    pull(count)
  
  interim_intervention_rank_n <- rank_summary_local %>%
    filter(as.character(condition) == "Intervention") %>%
    pull(count)
  
  interim_total_rank_n <- interim_control_rank_n + interim_intervention_rank_n
}

# Vector-safe formatters for mutate()
fmt_num_vec <- function(x, digits = 2) {
  ifelse(
    is.na(x),
    "NA",
    formatC(as.numeric(x), format = "f", digits = digits)
  )
}

fmt_p_vec <- function(p) {
  case_when(
    is.na(p) ~ "NA",
    p < .001 ~ "< .001",
    TRUE ~ paste0("= ", formatC(p, format = "f", digits = 3))
  )
}

interim_sig_dims <- character(0)

if (!is.null(stats_df_local)) {
  interim_sig_dims <- stats_df_local %>%
    filter(!is.na(p_value), p_value < .05) %>%
    arrange(p_value) %>%
    mutate(
      stat_text = paste0(
        dimension,
        " (t = ",
        fmt_num_vec(t_stat, 2),
        ", p ",
        fmt_p_vec(p_value),
        ", dz = ",
        fmt_num_vec(cohens_dz, 2),
        ")"
      )
    ) %>%
    pull(stat_text)
}

interim_sig_sentence <- if (length(interim_sig_dims) > 0) {
  paste0(
    "Dimension-wise paired comparisons indicated stronger intervention-related phenomenology for ",
    paste(interim_sig_dims, collapse = "; "),
    "."
  )
} else {
  "Dimension-wise paired comparisons did not identify any individual 6D-VHQ dimension reaching p < .05."
}

# ===================================================
# FIGURE 4 / WP2 FEASIBILITY VALUES
# Use Figure 1 assignment-counting logic for arm denominators:
# wp2_arm_counts = tested/analysed by condition from wp2_assign_clean
# ===================================================

ret_percent_local <- safe_get("ret_percent")
retention_df_local <- safe_get("retention_df")
summary_tol_local <- safe_get("summary_tol")
summary_tol_pooled_local <- safe_get("summary_tol_pooled")
tolerability_dropouts_local <- safe_get("tolerability_dropouts", NA_integer_)
wp2_arm_counts_local <- safe_get("wp2_arm_counts")

if (is.null(wp2_arm_counts_local)) {
  stop("wp2_arm_counts was not found. Please run Figure 1 before the narrative exporter.")
}

# Figure 1 denominators by arm
wp2_arm_denoms_f1 <- wp2_arm_counts_local %>%
  mutate(condition = as.character(condition)) %>%
  select(condition, n_randomised = tested, n_analysed = analysed)

# Session completion counts come from Figure 4 retention_df,
# but percentages use Figure 1's arm denominators.
if (is.null(retention_df_local)) {
  stop("retention_df was not found. Please run Figure 4 before the narrative exporter.")
}

ret_percent_narrative <- retention_df_local %>%
  select(session_n, Control, Intervention) %>%
  pivot_longer(
    cols = c(Control, Intervention),
    names_to = "condition",
    values_to = "count"
  ) %>%
  left_join(wp2_arm_denoms_f1, by = "condition") %>%
  mutate(
    percent_complete = 100 * count / n_randomised
  )

get_completion <- function(cond, sess) {
  out <- ret_percent_narrative %>%
    filter(as.character(condition) == cond, session_n == sess) %>%
    select(count, n_randomised, percent_complete)
  
  if (nrow(out) == 0) {
    tibble(count = NA, n_randomised = NA, percent_complete = NA)
  } else {
    out[1, ]
  }
}

control_s1 <- get_completion("Control", 1)
control_s4 <- get_completion("Control", 4)
intervention_s1 <- get_completion("Intervention", 1)
intervention_s4 <- get_completion("Intervention", 4)

max_tol_control <- NA_real_
max_tol_control_session <- NA_integer_
max_tol_intervention <- NA_real_
max_tol_intervention_session <- NA_integer_
max_tol_pooled <- NA_real_
max_tol_pooled_session <- NA_integer_

if (!is.null(summary_tol_local)) {
  tmp_control <- summary_tol_local %>%
    filter(as.character(condition) == "Control") %>%
    arrange(desc(mean)) %>%
    slice(1)
  
  tmp_intervention <- summary_tol_local %>%
    filter(as.character(condition) == "Intervention") %>%
    arrange(desc(mean)) %>%
    slice(1)
  
  if (nrow(tmp_control) > 0) {
    max_tol_control <- tmp_control$mean
    max_tol_control_session <- tmp_control$session_n
  }
  
  if (nrow(tmp_intervention) > 0) {
    max_tol_intervention <- tmp_intervention$mean
    max_tol_intervention_session <- tmp_intervention$session_n
  }
}

if (!is.null(summary_tol_pooled_local)) {
  tmp_pooled <- summary_tol_pooled_local %>%
    arrange(desc(mean)) %>%
    slice(1)
  
  if (nrow(tmp_pooled) > 0) {
    max_tol_pooled <- tmp_pooled$mean
    max_tol_pooled_session <- tmp_pooled$session_n
  }
}

# Optional audit print
cat("\nNarrative WP2 completion denominators using Figure 1 logic\n")
cat("=========================================================\n")
print(wp2_arm_denoms_f1)

cat("\nNarrative WP2 completion table using Figure 1 denominators\n")
cat("=========================================================\n")
print(ret_percent_narrative)

# ===================================================
# FIGURE 5 / CLINICAL OUTCOME VALUES
# ===================================================

phq_summary_local <- safe_get("phq_summary")
bdi_summary_local <- safe_get("bdi_summary")

get_score_endpoint <- function(summary_df, cond, first_tp = NULL, last_tp = NULL) {
  if (is.null(summary_df) || nrow(summary_df) == 0) {
    return(tibble(first_mean = NA, last_mean = NA, improvement = NA, first_tp = NA, last_tp = NA))
  }
  
  d <- summary_df %>%
    filter(as.character(condition) == cond) %>%
    arrange(tp)
  
  if (!is.null(first_tp)) d_first <- d %>% filter(as.character(tp) == first_tp) else d_first <- d %>% slice(1)
  if (!is.null(last_tp))  d_last  <- d %>% filter(as.character(tp) == last_tp)  else d_last  <- d %>% slice(n())
  
  if (nrow(d_first) == 0 || nrow(d_last) == 0) {
    return(tibble(first_mean = NA, last_mean = NA, improvement = NA, first_tp = NA, last_tp = NA))
  }
  
  tibble(
    first_mean = d_first$mean[1],
    last_mean = d_last$mean[1],
    improvement = d_first$mean[1] - d_last$mean[1],
    first_tp = as.character(d_first$tp[1]),
    last_tp = as.character(d_last$tp[1])
  )
}

phq_control <- get_score_endpoint(phq_summary_local, "Control")
phq_intervention <- get_score_endpoint(phq_summary_local, "Intervention")

bdi_control <- get_score_endpoint(bdi_summary_local, "Control")
bdi_intervention <- get_score_endpoint(bdi_summary_local, "Intervention")

phq_between_improvement_delta <- phq_intervention$improvement - phq_control$improvement
bdi_between_improvement_delta <- bdi_intervention$improvement - bdi_control$improvement

clinical_signal_sentence <- paste0(
  "For PHQ-9, mean scores changed from ",
  fmt_num(phq_control$first_mean, 2),
  " to ",
  fmt_num(phq_control$last_mean, 2),
  " in the Control arm and from ",
  fmt_num(phq_intervention$first_mean, 2),
  " to ",
  fmt_num(phq_intervention$last_mean, 2),
  " in the Intervention arm. ",
  "For BDI-II, mean scores changed from ",
  fmt_num(bdi_control$first_mean, 2),
  " to ",
  fmt_num(bdi_control$last_mean, 2),
  " in the Control arm and from ",
  fmt_num(bdi_intervention$first_mean, 2),
  " to ",
  fmt_num(bdi_intervention$last_mean, 2),
  " in the Intervention arm."
)

# ===================================================
# FIGURE 6 / EXPECTANCY + ACUTE EXPERIENCE VALUES
# ===================================================

pt_exp_local <- safe_get("pt_exp")
pt_asc_local <- safe_get("pt_asc")
delta_exp_local <- safe_get("delta_exp", NA_real_)
delta_asc_local <- safe_get("delta_asc", NA_real_)

split_summary <- function(df, score_col = NULL) {
  if (is.null(df) || nrow(df) == 0) {
    return(tibble(
      split_group = c("Low", "High"),
      n = NA_integer_,
      mean_pre = NA_real_,
      mean_post = NA_real_,
      mean_improve = NA_real_,
      mean_score = NA_real_
    ))
  }
  
  score_expr <- if (!is.null(score_col) && score_col %in% names(df)) {
    rlang::sym(score_col)
  } else {
    NULL
  }
  
  out <- df %>%
    group_by(split_group) %>%
    summarise(
      n = n(),
      mean_pre = mean(bdi_pre, na.rm = TRUE),
      mean_post = mean(bdi_post, na.rm = TRUE),
      mean_improve = mean(bdi_improve, na.rm = TRUE),
      .groups = "drop"
    )
  
  if (!is.null(score_expr)) {
    score_df <- df %>%
      group_by(split_group) %>%
      summarise(mean_score = mean(!!score_expr, na.rm = TRUE), .groups = "drop")
    out <- out %>% left_join(score_df, by = "split_group")
  } else {
    out$mean_score <- NA_real_
  }
  
  out
}

exp_split_sum <- split_summary(pt_exp_local, "expect_sum")
asc_split_sum <- split_summary(pt_asc_local, "asc_z")

get_split_row <- function(d, grp) {
  out <- d %>% filter(as.character(split_group) == grp)
  if (nrow(out) == 0) {
    tibble(
      split_group = grp,
      n = NA_integer_,
      mean_pre = NA_real_,
      mean_post = NA_real_,
      mean_improve = NA_real_,
      mean_score = NA_real_
    )
  } else {
    out[1, ]
  }
}

exp_low <- get_split_row(exp_split_sum, "Low")
exp_high <- get_split_row(exp_split_sum, "High")
asc_low <- get_split_row(asc_split_sum, "Low")
asc_high <- get_split_row(asc_split_sum, "High")

# ===================================================
# WRITE RESULTS SECTIONS
# ===================================================

section_310 <- paste0(
  "3.1.0. Programme Flow\n\n",
  "Across the three linked stages, ", fmt_n(wp1_screened_n), " participants were screened for WP1, ",
  fmt_n(interim_screened_n), " for the Interim study, and ", fmt_n(wp2_screened_n), " for WP2. Of these, ",
  fmt_n(wp1_analysed_n), ", ", fmt_n(interim_analysed_n), ", and ", fmt_n(wp2_analysed_n),
  " participants respectively contributed analysable data. Across the full programme, ", fmt_n(total_screened_n),
  " individuals were screened and ", fmt_n(total_analysed_n), " contributed analysable data to at least one stage. ",
  "Early WP1 recruitment proceeded under initially narrower eligibility criteria, before amendment of the screening approach broadened the eligible sample and reduced exclusion at intake. ",
  "Figure 1 summarises participant flow across the full programme, including standardised screening, exclusion, testing, and analysis counts for each stage, together with WP2 allocation and follow-up by study arm.\n\n",
  
  "Figure 1. Programme flow across the three-stage SLS programme. \n",
  "(A) Standardised screening, exclusion, testing, and analysis counts for WP1, the Interim study, and WP2. ",
  "(B) WP2 allocation and analysis flow by arm, showing ",
  fmt_n(control_s1$n_randomised), " participants allocated to Control and ",
  fmt_n(intervention_s1$n_randomised), " to Intervention, with analysable post-session-4 data available for ",
  fmt_n(control_s4$count), " and ", fmt_n(intervention_s4$count),
  " participants, respectively.\n"
)

section_3111 <- paste0(
  "3.1.1.1. Safety and Tolerability of Brief SLS Exposure\n\n",
  "WP1 was designed to establish whether brief laboratory SLS exposure could be delivered safely and tolerably in adults reporting depressive symptoms. ",
  "A total of ", fmt_n(wp1_tested_n), " participants were tested, of whom ", fmt_n(wp1_analysed_n),
  " contributed sufficient session-level tolerability data for analysis. Mean discomfort ratings remained low across the 11-session staircase protocol. ",
  "The highest session-wise mean discomfort was ", fmt_num(highest_mean_local, 2), "/10, and the highest one-sided 80% upper confidence limit was ",
  fmt_num(highest_ucl80_local, 2), "/10 at Session ", fmt_n(highest_ucl80_session_local), ". ",
  wp1_threshold_sentence, " ",
  "These findings support the acute tolerability of supervised SLS exposure under the tested conditions (Figure 2).\n\n",
  
  "Figure 2. WP1 session-wise discomfort and discontinuation-threshold context. \n",
  "(A) Mean discomfort/tolerability scores across the 11-session WP1 staircase protocol, shown with one-sided 80% upper confidence limits. ",
  "Shaded bands provide interpretive context for scores below 1 and above 1 on the 0–10 scale. ",
  "(B) Threshold-context display showing the highest observed one-sided 80% upper confidence limit relative to the prespecified discontinuation threshold of 7/10. ",
  "Across sessions, mean discomfort and upper confidence limits remained substantially below the threshold.\n"
)

section_3112 <- paste0(
  "3.1.1.2. Parameter Selection, Acceptability, and Acute Symptomatology\n\n",
  "Beyond safety, WP1 was used to identify parameter configurations that were sufficiently engaging for further development while remaining acceptable for repeated use. ",
  "Across the tested staircase, discomfort remained low even at the upper end of the observed session-wise confidence limits, indicating that the explored parameter space could be used to construct later intervention and control conditions without approaching the predefined discontinuation threshold. ",
  "Immediate post-session monitoring did not indicate systematic short-term worsening within the tolerability data available. ",
  "Overall, WP1 justified progression from one-off parameter testing to a repeated-session protocol.\n"
)

section_312 <- paste0(
  "3.1.2. Interim\n\n",
  "The Interim bridge study tested whether the proposed matched control condition reduced visual phenomenology while remaining a plausible comparator. ",
  "A total of ", fmt_n(interim_tested_n), " participants attended the Interim study, and all ",
  fmt_n(interim_analysed_n), " were included in the analysed dataset. ",
  "Across the 6D-VHQ dimensions, intervention sessions generally produced stronger visual phenomenology than control sessions. ",
  interim_sig_sentence, " ",
  "In the binary ranking task, the intervention session was selected as producing the greater visual experience ",
  fmt_n(interim_intervention_rank_n), " times, whereas the control session was selected ",
  fmt_n(interim_control_rank_n), " times, out of ", fmt_n(interim_total_rank_n),
  " total rankings. A one-sided binomial test against chance gave p ", fmt_p(binom_p_local), ". ",
  "Together, these findings support the internal-validity rationale for the low-phenomenology control condition used in WP2 (Figure 3).\n\n",
  
  "Figure 3. Interim validation of the low-phenomenology control condition. \n",
  "(A) Mean 6D-VHQ scores for Control and Intervention sessions across six visual phenomenology dimensions. ",
  "Bars show condition means, error bars show standard errors, and overlaid points show participant-level observations. ",
  "Intervention sessions produced higher scores for Geometric Content, Detail, Vividness, Focality, and Semantic Content, while Entropy showed no clear condition difference. ",
  "(B) Binary ranking counts indicating which session within each block was judged to produce the greater visual experience. ",
  "Intervention sessions were selected more often than Control sessions. ",
  "Asterisks indicate paired condition comparisons in Panel A and the one-sided binomial test in Panel B (*p < .05, **p < .01, ***p < .001).\n"
)

section_3131 <- paste0(
  "3.1.3.1. Repeated-Session Safety, Tolerability, and Feasibility\n\n",
  "WP2 evaluated whether repeated SLS could be delivered safely and practicably over four weekly supervised sessions. ",
  "A total of ", fmt_n(wp2_tested_n), " participants were randomised to WP2, of whom ",
  fmt_n(wp2_analysed_n), " contributed analysable post-session-4 data. ",
  "Session completion remained higher in the Intervention arm than in the Control arm across the protocol: Control completion changed from ",
  fmt_n(control_s1$count), "/", fmt_n(control_s1$n_randomised),
  " participants at Session 1 (", fmt_pct(control_s1$percent_complete, 1), ") to ",
  fmt_n(control_s4$count), "/", fmt_n(control_s4$n_randomised), " at Session 4 (",
  fmt_pct(control_s4$percent_complete, 1), "), whereas Intervention completion changed from ",
  fmt_n(intervention_s1$count), "/", fmt_n(intervention_s1$n_randomised),
  " (", fmt_pct(intervention_s1$percent_complete, 1), ") to ",
  fmt_n(intervention_s4$count), "/", fmt_n(intervention_s4$n_randomised), " (",
  fmt_pct(intervention_s4$percent_complete, 1), "). ",
  "Mean discomfort remained low across repeated sessions, with the highest observed mean discomfort occurring at Session 1 in both arms: ",
  fmt_num(max_tol_control, 2), "/10 in Control and ",
  fmt_num(max_tol_intervention, 2), "/10 in Intervention. ",
  "The highest pooled session-level mean discomfort was ", fmt_num(max_tol_pooled, 2),
  "/10 at Session ", fmt_n(max_tol_pooled_session), ". ",
  "A best-effort classification identified ", fmt_n(tolerability_dropouts_local),
  " discontinuations or missed completions with tolerability-related indicators. ",
  "Overall, the pattern supports the feasibility and repeated-session tolerability of supervised SLS in this population (Figure 4).\n\n",
  
  "Figure 4. WP2 feasibility and repeated-session tolerability. \n",
  "(A) Session completion percentages across the four-session WP2 protocol, shown separately for Control and Intervention arms. ",
  "Completion remained higher in the Intervention arm across later sessions. ",
  "(B) Mean discomfort scores across sessions by study arm. Error bars show standard errors. ",
  "Scores are plotted on a zoomed y-axis to show the observed range; mean discomfort remained low throughout the repeated-session protocol.\n"
)

section_3132 <- paste0(
  "3.1.3.2. Depressive Symptom and Affective Outcomes\n\n",
  "Clinical and affective outcomes in WP2 were interpreted as exploratory. ",
  clinical_signal_sentence, " ",
  "Expressed as mean improvement from baseline to endpoint, PHQ-9 change was ",
  fmt_num(phq_control$improvement, 2), " points in the Control arm and ",
  fmt_num(phq_intervention$improvement, 2), " points in the Intervention arm, corresponding to an intervention-minus-control improvement difference of ",
  fmt_signed(phq_between_improvement_delta, 2), " points. ",
  "For BDI-II, mean improvement was ", fmt_num(bdi_control$improvement, 2),
  " points in the Control arm and ", fmt_num(bdi_intervention$improvement, 2),
  " points in the Intervention arm, corresponding to an intervention-minus-control improvement difference of ",
  fmt_signed(bdi_between_improvement_delta, 2), " points. ",
  "These findings suggest a potentially meaningful clinical signal, particularly for BDI-II, but should be interpreted as hypothesis-generating rather than confirmatory evidence of efficacy (Figure 5).\n\n",
  
  "Figure 5. Exploratory depressive symptom change over WP2. \n",
  "(A) Mean PHQ-9 scores across the WP2 intervention period, including baseline, pre-session assessments, post-session 4, and 1-week follow-up. ",
  "(B) Mean BDI-II scores from baseline to post-treatment. Lines show study-arm means and error bars show standard errors. ",
  "Shaded bands indicate conventional symptom-severity ranges for each scale. ",
  "Clinical outcome analyses were exploratory and were not intended as confirmatory efficacy tests.\n"
)

section_3133 <- paste0(
  "3.1.3.3. Expectancy, Subjective Experience, and Candidate Predictors of Improvement\n\n",
  "Exploratory analyses examined whether baseline treatment expectancy or acute subjective experience tracked later improvement. ",
  "For expectancy, the lower-expectancy subgroup showed mean BDI-II improvement of ",
  fmt_num(exp_low$mean_improve, 2), " points, compared with ",
  fmt_num(exp_high$mean_improve, 2), " points in the higher-expectancy subgroup, yielding a high-minus-low improvement difference of ",
  fmt_signed(delta_exp_local, 2), " points. ",
  "For acute subjective experience, the lower acute-experience subgroup showed mean BDI-II improvement of ",
  fmt_num(asc_low$mean_improve, 2), " points, compared with ",
  fmt_num(asc_high$mean_improve, 2), " points in the higher acute-experience subgroup, yielding a high-minus-low improvement difference of ",
  fmt_signed(delta_asc_local, 2), " points. ",
  "Thus, expectancy showed comparatively little evidence of tracking improvement in this exploratory split-sample display, whereas stronger acute subjective experience appeared more closely associated with greater subsequent BDI-II reduction. ",
  "These candidate-predictor analyses should be interpreted as exploratory and hypothesis-generating rather than as evidence of mechanism (Figure 6).\n\n",
  
  "Figure 6. Exploratory BDI-II change stratified by expectancy and acute subjective experience. \n",
  "(A) Baseline-aligned BDI-II change from baseline to post-treatment for lower- and higher-expectancy subgroups. ",
  "(B) Baseline-aligned BDI-II change from baseline to post-treatment for lower and higher acute-experience subgroups. ",
  "Lines show subgroup means and error bars show standard errors. Shaded bands indicate conventional BDI-II severity ranges. ",
  "Δ values indicate the high-minus-low subgroup difference in mean BDI-II improvement. ",
  "These analyses were exploratory and are presented as candidate-predictor findings rather than evidence of mechanism.\n"
)

results_text <- paste(
  section_310,
  section_3111,
  section_3112,
  section_312,
  section_3131,
  section_3132,
  section_3133,
  sep = "\n\n"
)

cat("\n")
cat("============================================================\n")
cat("RESULTS NARRATIVE — AUTO-GENERATED FROM CURRENT R OBJECTS\n")
cat("============================================================\n\n")
cat(results_text)
cat("\n\n============================================================\n")

# ===================================================
# EXPORT TEXT + COMPACT NUMERIC AUDIT TABLE
# ===================================================

results_out_path <- file.path(NARRATIVE_OUT_DIR, "Results_Narrative_AutoGenerated.txt")
writeLines(results_text, results_out_path)

results_audit <- tibble::tribble(
  ~section, ~metric, ~value,
  "3.1.0", "WP1 screened", wp1_screened_n,
  "3.1.0", "Interim screened", interim_screened_n,
  "3.1.0", "WP2 screened", wp2_screened_n,
  "3.1.0", "WP1 analysed", wp1_analysed_n,
  "3.1.0", "Interim analysed", interim_analysed_n,
  "3.1.0", "WP2 analysed", wp2_analysed_n,
  "3.1.1.1", "WP1 highest mean discomfort", highest_mean_local,
  "3.1.1.1", "WP1 highest one-sided 80% UCL", highest_ucl80_local,
  "3.1.1.1", "WP1 rows >= threshold", wp1_rows_above_threshold,
  "3.1.2", "Interim control ranked higher count", interim_control_rank_n,
  "3.1.2", "Interim intervention ranked higher count", interim_intervention_rank_n,
  "3.1.2", "Interim binomial p", binom_p_local,
  "3.1.3.1", "Control session 4 completion percent", control_s4$percent_complete,
  "3.1.3.1", "Intervention session 4 completion percent", intervention_s4$percent_complete,
  "3.1.3.1", "Highest pooled WP2 mean discomfort", max_tol_pooled,
  "3.1.3.2", "PHQ Control improvement", phq_control$improvement,
  "3.1.3.2", "PHQ Intervention improvement", phq_intervention$improvement,
  "3.1.3.2", "BDI Control improvement", bdi_control$improvement,
  "3.1.3.2", "BDI Intervention improvement", bdi_intervention$improvement,
  "3.1.3.3", "Expectancy high-minus-low improvement delta", delta_exp_local,
  "3.1.3.3", "Acute experience high-minus-low improvement delta", delta_asc_local
)

audit_out_path <- file.path(NARRATIVE_OUT_DIR, "Results_Narrative_Audit_Values.csv")
readr::write_csv(results_audit, audit_out_path)

cat("\nSaved narrative to:\n")
cat(results_out_path, "\n")
cat("\nSaved audit values to:\n")
cat(audit_out_path, "\n")

#####################################################
#####################################################
#####################################################
#####################################################
#####################################################

# ===================================================

#####################################################
#####################################################
#####################################################
#####################################################
#####################################################

#####################################################
#####################################################
#####################################################
